# Generated by Django 5.2.7 on 2025-10-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrito', '0001_initial'),
        ('libros', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='carrito.carrito'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='ejemplar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.ejemplar'),
        ),
    ]
