# Generated by Django 5.2.7 on 2025-10-22 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20, unique=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('autores', models.ManyToManyField(related_name='titulos', to='libros.autor')),
            ],
        ),
        migrations.CreateModel(
            name='Ejemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('prestamo', 'Préstamo'), ('venta', 'Venta')], max_length=10)),
                ('codigo_interno', models.CharField(default='N/A', max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('reservado', 'Reservado'), ('mantenimiento', 'En mantenimiento'), ('dañado', 'Dañado')], default='disponible', max_length=20)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.titulo')),
            ],
        ),
    ]
